### PR TITLE
Add pattern matching discard example in bird watcher exercise #1014

### PR DESCRIPTION
**Pull request by aage**
Closes https://github.com/exercism/fsharp/issues/1014

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
Thanks!

**Comment by ErikSchierboom** [comment]
@aage Could you also add this information to the introduction.md and about.md of the arrays concept? See https://github.com/exercism/fsharp/blob/main/concepts/arrays/introduction.md and https://github.com/exercism/fsharp/blob/main/concepts/arrays/about.md

**Comment by aage** [comment]
@ErikSchierboom I've commited the same change to those docs as well.

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
