### PR TITLE
Remove Tree Building from core exercises

### PR DESCRIPTION
**Pull request by TeaDrivenDev**
This removes "Tree Building" from the core exercises on this track, to be able to go ahead with #739.

I'm wondering if it should be replaced by a similarly difficult exercise from the "side" pool, as this leaves the track with only 16 core exercises, which I feel isn't a lot, but I don't know the other exercises well enough to suggest one.

### CODE REVIEW

**Comment by TeaDrivenDev** [comment]
Okay, this fails because a few other exercises are set up to be unlocked by this one. I saw that when making the change, but thought it might not matter.

Do we just remap those to being unlocked by "Pig Latin" instead?

**Comment by ErikSchierboom** [comment]
> Do we just remap those to being unlocked by "Pig Latin" instead?

Yep!

**Comment by ErikSchierboom** [comment]
@TeaDrivenDev The build still fails unfortunately. Could you take a look?

**Comment by TeaDrivenDev** [comment]
@ErikSchierboom I'm not sure I can do much here. I ran the `test.ps1` script on my machine, and it runs for a while and outputs a lot of things, and then eventually stops with

```
Test Run Successful.
Total tests: 19
     Passed: 19
 Total time: 2,6347 Seconds
```

without dropping back to a prompt. As I don't fully understand what's happening here and have no working knowledge of PowerShell, I don't know how I would go about debugging this, or if that even makes sense.

**Comment by ErikSchierboom** [comment]
Weird. I'll take a look.

**Comment by ErikSchierboom** [comment]
@TeaDrivenDev I've found the issue. There is still one exercise (`sublist`) that is being unlocked by `tree-building`:

```
The exercise 'sublist' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises.
```

**Comment by TeaDrivenDev** [comment]
@ErikSchierboom Okay, fixed. Odd though that it didn't come up properly in the build errors as the other ones did.

**Comment by ErikSchierboom** [comment]
Great work! Thanks.

**Pull request merged**
