### PR TITLE
Add myself as mantainer

### PR DESCRIPTION
**Pull request by davidelettieri**

### CODE REVIEW

**Comment by robkeim** [comment]
Welcome @davidelettieri! Fingers crossed the script works to get you setup with the proper permissions :)

**Comment by ErikSchierboom** [comment]
Welcome @davidelettieri!

**Comment by davidelettieri** [comment]
Thanks guys! I was correctly invited into the organization so everything should be in place now 👍

**Comment by ErikSchierboom** [comment]
Great! Did you also get notified that there is a Slack channel for mentors/maintainers: https://exercism-team.slack.com?

If so, there is a [maintaining F# channel](https://exercism-team.slack.com/messages/CC526K1SB/details/).

**Comment by davidelettieri** [comment]
I think I need an invitation to join the slack channel

**Comment by ErikSchierboom** [comment]
@iHiD Do you know how that works?

**Comment by iHiD** [comment]
Easiest way is to become a mentor and there's a link on the RHS of the mentor dashboard.

**Pull request merged**
