### PR TITLE
Update canonical data to latest version

### PR DESCRIPTION
**Pull request by robkeim**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Thanks again!

**Comment by ErikSchierboom** [comment]
@robkeim By the way, moving to GitHub Actions has helped "a bit." Instead of taking over an hour for all tests to run, they now run in...6 minutes! https://github.com/exercism/fsharp/commit/562c23b56021db7d3087da4e92ee64eccddd040d/checks?check_suite_id=354120188

**Comment by robkeim** [comment]
That's a HUGE improvement :)

**Comment by davidelettieri** [comment]
Great work guys!

**Pull request merged**
