### PR TITLE
Add dependabot support

### PR DESCRIPTION
**Pull request by ErikSchierboom**
@robkeim This is an attempt to add support for dependabot to the F# track, including the suggestions made in https://github.com/exercism/csharp/pull/984.

### CODE REVIEW

**Comment by robkeim** [comment]
Looks good to me, thanks @ErikSchierboom!

**Comment by ErikSchierboom** [comment]
The number of PR's now looks a lot more manageable :) Thanks for the hint @greysteil!

**Comment by greysteil** [comment]
Great to hear!

**Comment by robkeim** [comment]
@ErikSchierboom I'm not sure that it's batching them together. I think we're just running into the limit of 5 PRs since it's a new branch:
> **Note:** This repo was added to Dependabot recently, so you'll receive a maximum of 5 PRs for your first few update runs. Once an update run creates fewer than 5 PRs we'll remove that limit.

https://github.com/exercism/fsharp/pull/684

**Comment by robkeim** [comment]
It looks like it's not processing all of the files:

image


For csharp, I can see all of the different csproj's.

**Comment by greysteil** [comment]
It's got them. If you hover/click on that (...) symbol it will have the other files - it's just that they're bundled together in a single update config (and hence the PRs will be bundled together, too).

**Comment by ErikSchierboom** [comment]
Here's confirmation of the above statement:

image

@robkeim It looks like all projects are properly tracked.

**Comment by robkeim** [comment]
Ah ok I see it now, thanks!

I found a PR where things are bundled too:
https://github.com/exercism/fsharp/pull/689

Thanks for helping us get this setup @greysteil!

**Comment by ErikSchierboom** [comment]
It's like magic!

**Pull request merged**
