### PR TITLE
Explain how to run tests

### PR DESCRIPTION
**Pull request by hickford**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Hi @hickford! First of all, thanks for the contribution, we really appreciate it. If I understand correctly, with this PR you aim to help people get started by being explicit about how to run your tests. This is an excellent addition, although I'd like to request a small change.

Instead of changing the README.md file itself (which is auto-generated), you can add an exercise-specific HINTS.md (in the exercise's `.meta` directory). The contents from this HINTS.md file can then automatically be appended to the default README's contents, which makes it a more futureproof way of adding additional information. Could you undo the changes to the README and add the information to a `.meta/HINTS.md` file in the exercise's directory?

For an example of another exercise that has a HINTS.md file, see https://github.com/exercism/fsharp/blob/7cb2851b61795183acde4c4877f7b3ae5a76a914/exercises/gigasecond/.meta/hints.md.

**Comment by hickford** [comment]
Thanks Erik for your reply. Good idea, will follow the example

**Comment by ErikSchierboom** [comment]
@hickford Are you still interested in working on this PR?

**Comment by ErikSchierboom** [comment]
Hi! As there was no reply, this was picked up as part of #569. I'm gonna close this. Thanks for the contribution!

**Pull request closed without merging**
