### PR TITLE
improve performance of example implementation

### PR DESCRIPTION
**Pull request by davidelettieri**
Regarding #642 pythagorean triplet is an exercise with some straightforward performance improvements.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@davidelettieri Looking good. Did you by any chance do some performance measurements?

**Comment by davidelettieri** [comment]
Sure, on my pc before my changes it was taking 10s to run the tests, now is down to 3s

**Comment by ErikSchierboom** [comment]
Great to hear! Thanks for doing this. Are there are slow tests remaining?

**Comment by davidelettieri** [comment]
I think palindrome products could be improved since it's taking 9 sec on my pc to run the tests, I'll start working on it today.

However pythagorean triplets and alphametics are still slower than all the other projects.

**Comment by ErikSchierboom** [comment]
Cool. I think once palindrome-products has been sped up a bit, we can consider this to be done. Alphametics and pythagorean triplets are exercises that do require some number crunching, but their performance is now good enough I feel. Awesome work!

**Pull request merged**
