### PR TITLE
Ensure PowerShell errors are propagated

### PR DESCRIPTION
**Pull request by ErikSchierboom**
When issue https://github.com/exercism/csharp/issues/1299 was created, I found out that there was something wrong with our build pipeline. The [CI run](https://travis-ci.org/exercism/csharp/builds/554366818?utm_source=github_status&utm_medium=notification) had an error, but Travis still thought that it was a succesful build. Apparently, one has to be explicit about returning the error code of called scripts, which is what this PR adds.

### CODE REVIEW

**Comment by robkeim** [comment]
It looks like the markdown exercise now isn't working on the F# track with the latest canonical data updates.

Sorry about getting us into this mess... I updated the tests and figured I'd let the CI check to see if there were any build errors not realizing that we had this bug.

**Comment by ErikSchierboom** [comment]
> Sorry about getting us into this mess... I updated the tests and figured I'd let the CI check to see if there were any build errors not realizing that we had this bug. 

No problem. I completely missed this as a reviewer, and relying on the CI makes very much sense.

**Comment by ErikSchierboom** [comment]
The markdown issue is likely the same that was fixed in [this commit](https://github.com/exercism/csharp/commit/4ff720d5e6463a72a471d7115d7139fcff84caac) in the C# repository.

**Comment by ErikSchierboom** [comment]
@robkeim I've fixed all the build issues.

**Comment by robkeim** [comment]
Great work, thanks @EricSchierboom for getting us back into good shape! :+1:

**Pull request merged**
