### PR TITLE
Test case generation for perfect-numbers.

### PR DESCRIPTION
**Pull request by vrnithinkumar**
Added test case generation for perfect-numbers fIx for #391.
Added a InvalidInput in classification for invalid input data. 
Updated the example to support invalid input case.

### CODE REVIEW

**Comment by robkeim** [comment]
@ErikSchierboom I agree with what you said and would also be in favor of option 3.

**Comment by vrnithinkumar** [comment]
Option 3 seems like more apt to me. I will make those changes. @ErikSchierboom Please have a look.

**Comment by ErikSchierboom** [comment]
The changes look good! The CI build failed for weird reasons, so I've just restarted the build. Once it is green, I'll merge.

**Comment by ErikSchierboom** [comment]
There is something wrong with Travis. Will look into

**Comment by ErikSchierboom** [comment]
And the build is back! Merged. Thanks a lot. :tada:

**Pull request merged**
