### PR TITLE
Remove AppVeyor and CircleCI integration

### PR DESCRIPTION
**Pull request by ErikSchierboom**
See #345

### CODE REVIEW

**Comment by robkeim** [comment]
@ErikSchierboom the changes look good to me. Do we need to force merge this or wait until @kytrinyx removes AppVeyor and CircleCI as you asked in #345?

**Comment by kytrinyx** [comment]
If you push an empty commit to this (and then force push again without it) this should rebuild properly.

**Comment by ErikSchierboom** [comment]
I've just added an reverted a space change.

**Comment by robkeim** [comment]
Thanks @ErikSchierboom 🎉

**Pull request merged**
