### PR TITLE
Add new test for grade-school exersice

### PR DESCRIPTION
**Pull request by Grenkin1988**
Hello,

Exercise have this description:

> Get a sorted list of all students in all grades. Grades should sort as 1, 2, 3, etc., and students within a grade should be sorted alphabetically by name.
"Who all is enrolled in school right now?"
"Let me think. We have Anna, Barb, and Charlie in grade 1, Alex, Peter, and Zoe in grade 2 and Jim in grade 5. So the answer is: Anna, Barb, Charlie, Alex, Peter, Zoe and Jim"

Given that all tests are using `add` function as part of the `school` preparation, we never test that `roster` function handles the case when input `school` was not sorted.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Thanks for the PR, but I'm not sure we should be merging this. The problem with the newly added test is that it forces an implementation upon the student. We deliberately don't force the student to use a map, as they're then free to implement as they see fit.

**Comment by Grenkin1988** [comment]
> Thanks for the PR, but I'm not sure we should be merging this. The problem with the newly added test is that it forces an implementation upon the student. We deliberately don't force the student to use a map, as they're then free to implement as they see fit.

Sorry I do not 100% understand this. Do you mean that it is OK for student to remove type alias and do something else instead?

**Comment by ErikSchierboom** [comment]
Oh the type alias is still there? I thought I had removed that 😕 It's fine then!

**Review by ErikSchierboom — APPROVED** [review]

**Comment by Grenkin1988** [comment]
Yes, it uses `type School = Map<int, string list>`

**Pull request merged**
