### PR TITLE
add generators and test for pov challenge #394

### PR DESCRIPTION
**Pull request by roman-shuhov**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Thanks a lot! 🎉

**Comment by ErikSchierboom** [comment]
@roman-shuhov You submissions have consistently been of very high quality. I was wandering if you are perhaps interested in becoming an official maintainer of the F# track? Being a maintainer does not actually require you to invest a lot of time, at the minimum it involves reviewing submitted PR's. If you'd like to do more, you can help improve documentation, add new exercises, cleanup the existing ones, etc. But those are all optional.

Let me know what you think. If you don't feel like becoming an official maintainer, no worries!

**Comment by roman-shuhov** [comment]
@ErikSchierboom i've somehow missed this message. I would love to if it's not too late :)

**Comment by ErikSchierboom** [comment]
I'm sorry but currently all generators have been added

**Pull request merged**
