### PR TITLE
Rename sut to actual #1003

### PR DESCRIPTION
**Pull request by aage**
Thought this would be an improvement

### CODE REVIEW

**Comment by aage** [comment]
@ErikSchierboom Maybe I don't understand, but if  I change *actual* back to *sut*, what would be the purpose of this PR?

**Comment by ErikSchierboom** [comment]
@aage Doh, I wasn't paying attention. This is totally fine. Could you run the generator (`dotnet run --exercise zipper`) to re-generate the `ZipperTests.fs` file?

**Comment by aage** [comment]
@ErikSchierboom I've commited and pushed the updated `ZipperTests.fs` file.

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
