### PR TITLE
Looks like tests not consistent

### PR DESCRIPTION
**Pull request by aivanov-oneinc**
Tests expected results contains 7 notes and contains 7 interval description for them the same time. Looks like interval has one extra item. It's impossible to have 7 intervals between 7 notes. Only 6 intervals might be between 7 notes
If I remove the last item from interval tests tun OK

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Hi! Great find. The test suite you mention is actually based on some shared data that you can find here: https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/canonical-data.json

Would you mind opening an issue on that repository: https://github.com/exercism/problem-specifications/issues? That would, we can get it fixed there and all tracks can benefit from this change.

**Comment by aivanov-oneinc** [comment]
@ErikSchierboom done. https://github.com/exercism/problem-specifications/issues/1425

I'll also create pull request there.

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by ErikSchierboom** [comment]
Seeing how https://github.com/exercism/problem-specifications/issues/1425 is closed, I'll also close this one. If you think that should not be the case, feel free to let me know @aivanov-oneinc

**Pull request closed without merging**
